### ISSUE TITLE
running time / stuck

### ISSUE THREAD

**Issue by ereyred** [labxscut/elsa#1]
Hello,
I've run:
lsa_compute -r 1 -s 18 -t Med -d 2 eLSAin.txt Rall-eLSAout

And it's been running for 4 days now, no errors, stuck at:

lsa_compute (rev: v1.0.2@GIT: c0bb9dd) - copyright Li Charlie Xia, lixia@stanford.edu
delayLimit      minOccur        fillMethod      pvalueMethod    precision       dataFile        extraFile       resultFile      repNum  spotNum bootNum transFunc     normMethod      approxVar       trendThresh
2       50      none    perm    1000    Rall-gen-for-eLSA.txt           Rall-eLSAout    1       18      0       Med     robustZ 1       None
firstData factorNum, repNum, spotNum = 986, 1, 18
secondData factorNum, repNum, spotNum = 986, 1, 18
calculating  972196 pairwise local similarity scores...
inside applyAnalysis...
pairwise calculation...

Is it broken or just running slowly? The output file so far is empty.
How long does eLSA normally take? Is it taking so long because there's so many factorNum and spotNum?
Also is it absolutely essential to have replicates? My data has no replicates.

Thanks for your help!
E

**Comment by chaelir** [comment]
this perm time will be hell, suggest you to use theo
